trigger:
- master
pr:
- master
jobs:
- job: run_tests
  displayName: Run Unit Tests
  pool:
    name: fulcrum
  steps:
    - script: |
        CARGO=$HOME/.cargo/bin/cargo
        $CARGO suity
      displayName: Run Tests
    - task: PublishTestResults@2
      inputs:
        testRunner: JUnit
        testResultsFiles: 'test-results/default.xml'
        failTaskOnFailedTests: true

