trigger:
- master
pr:
- master
jobs:
- job: run_tests
  displayName: Run Unit Tests
  pool:
    name: fulcrum
  strategy:
    matrix:
      stable:
        rustup_toolchain: stable
      beta:
        rustup_toolchain: beta
      nightly:
        rustup_toolchain: nightly
  steps:
    - script: |
        CARGO=$HOME/.cargo/bin/cargo
        $CARGO suity
      displayName: Run Tests
    - task: PublishTestResults@2
      inputs:
        testRunner: JUnit
        testResultsFiles: 'test-results/default.xml'
        failTaskOnFailedTests: true

