trigger:
- master
pr:
- master
jobs:
- job: run_tests
  displayName: Run Unit Tests
  variables:
    zol_rel: "0.7.12"
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      stable:
        rustup_toolchain: stable
      beta:
        rustup_toolchain: beta
      nightly:
        rustup_toolchain: nightly
  steps:
    - script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: Install rust
    - script: |
        CARGO=$HOME/.cargo/bin/cargo
        RUSTFLAGS="-C link-dead-code" $CARGO test --no-run
        cargo install cargo-suity
        RUSTFLAGS="-C link-dead-code" $CARGO suity
      displayName: Run Tests
    - script: |
        RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
        sudo RUSTFLAGS="-C link-dead-code" $(which cargo) tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)
      displayName: Run Coverage
      condition: and(succeeded(),eq(variables['rustup_toolchain'], 'nightly'))
    - task: PublishTestResults@2
      inputs:
        testRunner: JUnit
        testResultsFiles: 'test-results/default.xml'
        failTaskOnFailedTests: true

